# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBADpU_dANi-GC_ZklJZqGF2IiEm_WZg
"""

height = input()
weight = input()
bmi = float(weight)/float(height)**2
print(int(bmi))