# -*- coding: utf-8 -*-
"""DataTypesExercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBADpU_dANi-GC_ZklJZqGF2IiEm_WZg
"""

two_digit_number = input()
total = int(two_digit_number[0]) + int(two_digit_number[1])
print(total)

