# -*- coding: utf-8 -*-
"""LifeinWeeks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBADpU_dANi-GC_ZklJZqGF2IiEm_WZg
"""

age = input()
max_age = 90
max_weeks = max_age * 52
age_in_weeks = int(age) * 52
remaining_weeks = int(max_weeks) - int(age_in_weeks)
print(f"You have {remaining_weeks} weeks left.")