# -*- coding: utf-8 -*-
"""Split Bill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBADpU_dANi-GC_ZklJZqGF2IiEm_WZg
"""

print('Welcome to the trip calculator!')
total_bill = (input("What was the total bill? $"))
tip = input("How much tip would you like to give? 10, 12, or 15?")
people_split_bill = input("How many people to split the bill?")

#Operation
calc_tip = 1.00 + int(tip)/100
split_bill = int(total_bill)/int(people_split_bill) * calc_tip
final_bill = round(split_bill, 2)

print(f"Each person should pay: ${final_bill}")